### ISSUE TITLE
The website URL is not valid. 

### ISSUE THREAD

**Issue by Djalin** [phpservermon/phpservermon#819] opened 2019-12-06 17:13 UTC
Hello, this appears even at the address given in the example.
http://sourceforge.net/index.php

http://i.imgur.com/6985EVk.png

And the checks are successful

**Comment by TimZ99** [comment] 2019-12-06 17:18
Hmmm, I guess you use latest commit?
The regex got an update, will have a look at it.

**Comment by Djalin** [comment] 2019-12-06 19:09
> Hmmm, I guess you use latest commit?

yes

which version do you recommend with telegramm support?

**Comment by TimZ99** [comment] 2019-12-09 23:09
Duplicate of #816.

**Closed as completed** 2019-12-09 23:09 UTC

**Comment by f4hbg** [comment] 2024-05-17 13:44
hi, PHP Server Monitor v3.5.2. / debian 12.5 / Apache/2.4.59 (Debian)  / PHP 8.2.18
same problem back again
can't even modify existing entries
have the red msg "The website URL is not valid."
