### ISSUE TITLE
users area sending 500 error code cannot finish software implementation

### ISSUE THREAD

**Issue by yonatonreid** [phpservermon/phpservermon#817] opened 2019-12-05 05:04 UTC
i just setup the software, which is working great. i added 2 sites and i am trying to add new users so i can attach them to monitoring emails but when i click on users it has a apache 500 error.

**Comment by TimZ99** [comment] 2019-12-11 22:04
Can't reproduce.

**Comment by Mickroz** [comment] 2019-12-13 10:08
im getting same error when visiting ?&mod=user
apache access_log only shows "GET /?&mod=user HTTP/1.1" 500 -
error_log shows nothing.
```
error_reporting(E_ALL);
ini_set("display_errors", 1);
```
not returning anything.
running on PHP Version 7.3.9 and Apache/2.4.41 on Linux 5.3.1-arch1-1-ARCH.
tested on Chrome, Firefox, Opera and Edge.

**Comment by wienfuchs** [comment] 2019-12-13 10:47
> /?&mod=user

Did you re-check on latest commits? Sounds like the https://github.com/phpservermon/phpservermon/commit/7e3cbc94a95a736781bc388504247a0c0c598e33 commit to me.

**Comment by Mickroz** [comment] 2019-12-13 10:54
ah that could be it, had some more issues with mcrypt on other projects.
I have v3.4.5 installed, will install latest and see.

edit:
hmm i had 3.2.0 installed :O updated to developer download, and it works now!

**Comment by TimZ99** [comment] 2019-12-13 12:02
😄 maybe that's why I couldn't reproduce. 

I made an issue template yesterday to prevent those kinds of 'miscommunications'. 
Glad that we fixed it and it's working for you 👍. This update will be in V3.5.0 and will be released very soon.

**Closed as completed by TimZ99** 2019-12-13 12:02 UTC
Labels: Status: needs more info
