### ISSUE TITLE
SSL checks

### ISSUE THREAD

**Issue by codeagencybe** [phpservermon/phpservermon#591] opened 2018-05-28 12:20 UTC
Add option to check SSL certificates expiry and sent pre-alert when certificate is about to expire

**Comment by TimZ99** [comment] 2018-05-28 12:25
There already is a pr for this, but it needs to be rebased and there are a few things that need to be changed.

**Comment by TimZ99** [comment] 2018-09-04 18:02
Duplicate of #384

**Closed as completed by TimZ99** 2018-09-04 18:02 UTC
Labels: duplicate
