### ISSUE TITLE
Fail time is not correct.

### ISSUE THREAD

**Issue by RicRey1988** [phpservermon/phpservermon#759] opened 2019-07-30 18:57 UTC
I created a test vps and I realized that I left it 3 minutes offline or 2 hours at the time of reactivating the message that arrives is that it was only down 2.40 seconds, something that is incorrect ...

How can this be resolved?

I use version 3.4.0

**Comment by TimZ99** [comment] 2019-09-25 21:48
Do you have this problem more often? Did you run PSM via CRON?

**Comment by mefisto22** [comment] 2019-10-02 11:27
I have this issue. I run update from website. Update time is correct for 2-3 minutes. After this time show last check 2 hour. In mysql database show after 2-3 minutes, servers was updated two hours early.

**Comment by dktcoding** [comment] 2019-10-10 05:21
This is still an issue on v3.4.5.

I believe this is related to https://github.com/phpservermon/phpservermon/commit/b26f85d975bcfacad2d3439fc41958ddf9c1009f#r34560074

**Comment by mefisto22** [comment] 2019-10-12 12:11
I solved this problem. Problem was in php.ini files. On linux we have 3 php.ini file. I changed only one file. When i changed timezones in all php.ini, problem was solved.

**Comment by TopicsLP** [comment] 2020-04-25 17:48
I currently encounter this problem (v3.4.5), that the downtime window is always wrong, and never excedes one minute.

The issue is only there if the "status.cron.php" is run by the system crontask.

If i use the Update button on the WebInterface it is working correclty.

**Comment by TopicsLP** [comment] 2020-04-25 19:31
I think this issue is the same as #825 
And is fixed with: b742629

**Closed as completed** 2020-05-17 21:14 UTC
Labels: Status: needs more info
