### ISSUE TITLE
[BUG] Upgrade 3.4.5 to 3.5 Fatal Error

### ISSUE THREAD

**Issue by AlexandreKz** [phpservermon/phpservermon#964] opened 2020-07-29 08:21 UTC
Can't upgrade version 3.4.5 to 3.5
On step "Navigate to install.php" from documentation, i reciev fatal error:
`Fatal error: Namespace declaration statement has to be the very first statement or after any declare call in the script in /var/www/mon/install.php on line 33`

I also receive this message during a "clear" installation.

 - Version 3.4.5 to 3.5
 - PHP 7.1
 - Ubuntu 16.04

**Comment by AlexandreKz** [comment] 2020-07-31 19:40
Check on php 7.2 - this message also falls out

**Comment by wienfuchs** [comment] 2020-08-01 05:43
This maybe a duplicate of https://github.com/phpservermon/phpservermon/issues/908 - could you try downloading the changed files from https://github.com/phpservermon/phpservermon/pull/915/files to your local installation ad recheck if your problem has gone? Only three files required from there:
``src/psm/Module/Install/Controller/InstallController.php``
``src/psm/Module/User/UserEvents.php``
``src/psm/Util/Module/Modal.php``

**Comment by AlexandreKz** [comment] 2020-08-05 10:21
Yes, it really helped me. Thank you so much

**Closed as completed** 2020-08-05 10:21 UTC
Labels: Type: bug
