### ISSUE TITLE
Status page block to show SSL cert days to expiry

### ISSUE THREAD

**Issue by jckruger** [phpservermon/phpservermon#510] opened 2017-09-04 06:59 UTC
Something like this. What files would need to be changed to show this. I don't see any reference to the actual cert date in the database only the threshold set

![image](https://user-images.githubusercontent.com/20898927/30014764-594239d8-9191-11e7-9140-cacf572ddcf2.png)

Also when the expiry is lower than the threshold set can the test still run but show another color maybe Purple

**Comment by jckruger** [comment] 2017-09-06 12:22
Well at least I have now got the error or status to show up on the block and list page from editong this file
/src/templates/default/module/server/status/index.tpl.html
I could have added it to the language file but I am only going to use EN_US and am lazy

![image](https://user-images.githubusercontent.com/20898927/30111594-9f03eb80-9351-11e7-8c9b-2324402c7492.png)


[index.tpl.txt](https://github.com/phpservermon/phpservermon/files/1281031/index.tpl.txt)

**Comment by TimZ99** [comment] 2018-09-04 18:01
The expiration date is not saved to the database. I think I'm going to make the block yellow if the expiration date is within a certain time (to be determined by the user). 
The threshold is used for something else than an ssl check, so that's not going to work.

**Comment by TimZ99** [comment] 2018-09-04 18:03
Duplicate of #384

**Closed as completed by TimZ99** 2018-09-04 18:03 UTC
Labels: duplicate
