### ISSUE TITLE
Possibility to set requested status code

### ISSUE THREAD

**Issue by bastians** [phpservermon/phpservermon#260] opened 2016-02-20 16:46 UTC
It would be very useful have the possibility to set the requested status code. If the requested status code doesn't match with the status code from the given url, the status of the site is "offline".

**Comment by sadortun** [comment] 2016-04-30 10:34
Good idea, we are accepting PR. 

#102

**Comment by bastians** [comment] 2016-05-16 11:54
Can anyone help me with the PR?

**Comment by sadortun** [comment] 2016-05-22 02:54
Duplicate of #175

**Closed by sadortun** 2016-05-22 02:54 UTC
Labels: enhancement, needs PR
