### ISSUE TITLE
after latest update ping type not working.

### ISSUE THREAD

**Issue by PirSoft** [phpservermon/phpservermon#529] opened 2017-10-25 10:15 UTC
hi dear;
after last update. ping type is not working.  
select type and save. and click edtit > type = please select.
what is problem?

**Comment by PirSoft** [comment] 2017-10-25 10:15
all others not working stable.

**Comment by tjharman** [comment] 2017-10-25 18:44
Duplicate of #500

**Comment by PirSoft** [comment] 2017-10-27 05:44
ok. i resolved problem. need new installation.  old database problem about this issue. need check old database update.

**Closed as completed** 2018-04-25 11:59 UTC
