### ISSUE TITLE
I receive mail with question marks when using non-English characters?

### ISSUE THREAD

**Issue by baur** [phpservermon/phpservermon#378] opened 2016-11-15 11:04 UTC
I receive mail with question marks when using non-English characters?

?????????? ???????????? ? ?????????? ???????:

??????: ???????
IP: 10.28.XXX.XXX
????: 1
??????: 
????: 2016-11-15 11:43:52

**Comment by baur** [comment] 2016-11-15 11:16
but "send test mail" works fine with utf-8

**Comment by sadortun** [comment] 2016-11-15 18:07
Duplicate of #350

**Closed by sadortun** 2016-11-15 18:07 UTC
Labels: bug, Open for contribution
