### ISSUE TITLE
[Feature Request] View by Group

### ISSUE THREAD

**Issue by breaker84** [phpservermon/phpservermon#621] opened 2018-08-16 02:16 UTC
Dear all, 1st of all, this is the best app to monitor....
I would like to suggest that the app have sort of grouping function, so that we can view the dashboard according to the group...
we have almosy 50 device to be monitor...
and we can grouping it for:
1. website
2. system for staff
3. feedback system device
4. etc.

regards

**Comment by TimZ99** [comment] 2018-08-16 22:41
Duplicate of #565

**Closed as completed by TimZ99** 2018-08-16 22:41 UTC
Labels: duplicate
