### ISSUE TITLE
Blank page for history page

### ISSUE THREAD

**Issue by PushinoRU** [phpservermon/phpservermon#970] opened 2020-08-06 09:15 UTC
Dear Team !
i have installed PSM 3.5 with  last php version (7.4) on the virtual esxi mashine
After install version i added more ten servers and was be happy.
The PSM good worked two days, and them i can't see history server page  (?&mod=server&action=view&id=39&back_to=server_status)  . the request to the page returned blank page.
i checked litle investigation and  find problem in quantity of records  of mysql table  psm_servers_uptime 
i can see more 900000 records, after drop records i  can see the page has returned is normal state. 
For workaround i'm created procedure and new table for archive records  with same structure the procedure every two days moved records to archive table

**Comment by milux** [comment] 2020-08-13 05:36
duplicate of #625?

**Closed as completed** 2020-08-13 14:31 UTC
Labels: Type: bug
