### ISSUE TITLE
Operation Not Permitted - Sockets and Ping

### ISSUE THREAD

**Issue by Puyodead1** [phpservermon/phpservermon#686] opened 2018-12-03 12:40 UTC
Ubuntu 18.04 with Apache2, sockets are enabled but i get the error Operation Not Permitted

**Comment by Rayne** [comment] 2018-12-03 17:11
This is a duplicate of the open issue https://github.com/phpservermon/phpservermon/issues/684.

**Closed as completed** 2018-12-04 12:46 UTC
