### ISSUE TITLE
[BUG] SSL Cert check does not work v3.4.6-beta.3

### ISSUE THREAD

**Issue by sicutdeux** [phpservermon/phpservermon#896] opened 2020-04-30 20:47 UTC
Added a website that i know the cert needs to be renewed (Lets), and no matter how much i put the time on the config of the site it gets detected or throws a warning.

If i put the https:// does not give warning
if i put the http:// marks the sites as warning even if the cert is valid for the time assigned on the config.
sites has redirection to https with 302

 - Version  v3.4.6-beta.3.
 - PHP 7.3.17 (FPM)
- Centos 7 Using NGINX

**Comment by wienfuchs** [comment] 2020-05-01 01:18
Just checked in in 3.5.0 - seems to work fine. Can you recheck?

**Comment by sicutdeux** [comment] 2020-05-01 03:32
I'm using: Version v3.4.6-beta.3. since i cloned the repo this morning, and i see now that the tag for dev is 3.5.0 i can test later, going to bed now.

**Comment by sicutdeux** [comment] 2020-05-01 23:00
Well updated to 3.5.0 but no luck having the certs detected when expires.

i see this:

```
Last positive output:
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 01 May 2020 22:47:11 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Set-Cookie: PHPSESSID=3aa5285bef1dc34ef553fb04d806bc87; path=/
Expires
```

but the Expires gets truncated (this is on edit server view)

I have setup the server as a website, the url contains https:// also a added a pattern to indicate the site is online, the redirects to another site is marked as bad.

Cert for this test expires in July 2020 and i set validity days 365, so it should mark it as Warning, but nothing.

**Comment by wienfuchs** [comment] 2020-05-02 05:47
Well, as with me and Letsencrypt cert's it works. It also works with google and 700 days, as expected
![grafik](https://user-images.githubusercontent.com/44177781/80856296-f4c05200-8c48-11ea-897b-5817a79e4113.png)
Maybe you could supply an URL on which it does not work? Maybe also the config for that?

**Comment by wienfuchs** [comment] 2020-05-02 05:50
> i see this:
> ```
> Set-Cookie: PHPSESSID=3aa5285bef1dc34ef553fb04d806bc87; path=/
> Expires
> ```
> 
> but the Expires gets truncated (this is on edit server view)

Btw - this "Expires" line is related to the HTTP header, which shows only the expiration of the cache for the single webpage. This does not relate to the certificate expiration, which must be read from the certificate itself.

**Comment by sicutdeux** [comment] 2020-05-02 17:39
Ok, just created google same as you, with 700 days to check the cert and still green here
![image](https://user-images.githubusercontent.com/8029652/80871370-2d2c5400-8c7a-11ea-8ea3-a1416b20889f.png)

This is the config i set for google, nothing out of the ordinary:

![image](https://user-images.githubusercontent.com/8029652/80871390-5220c700-8c7a-11ea-99b4-812b1e82dd56.png)

**Comment by wienfuchs** [comment] 2020-05-02 17:52
Maybe you want to try switching the reqest methiod to "GET" instead of "NONE"?
What PHP Version do you use?
What "Registered Stream Socket Transports" are shown when you issue phpinfo(); in any php file?

**Comment by sicutdeux** [comment] 2020-05-02 17:56
I changed to GET, lets wait, but i think that will not work since the original site has GET.

`Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv3, tls, tlsv1.0, tlsv1.1, tlsv1.2
`
```
PHP 7.3.17 (cli) (built: Apr 14 2020 08:29:22) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.17, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.17, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by wienfuchs** [comment] 2020-05-02 18:01
Very strange, as you have even more streams enabled then me ... just to make sure: curl support is enabled, including ssl enabled (another phpinfo(); check)? Openssl then as well ...

**Comment by sicutdeux** [comment] 2020-05-02 18:07
Attaching the output of php -i, everything looks normal. 
[info.txt](https://github.com/phpservermon/phpservermon/files/4568498/info.txt)

**Comment by wienfuchs** [comment] 2020-05-02 18:17
The only major diff relating to SSL between your and my config I can see is the OpenSSL Library Version - you are using 1.0.2k, I am using 1.1.1g. Maybe this issues the problem? If I find some time, I may have a look into how the specific check is adressed - or maybe @TimZ99 may check this direct?

**Comment by TimZ99** [comment] 2020-05-06 20:46
I get the correct warning state too. Think OpenSSL made some breaking changes in between the version

**Comment by n0nag0n** [comment] 2020-05-18 19:36
So I've looked into this cause I really wanted it to work and looking at why one of my sites with a very expired cert wasn't being caught on. Let me tell you what I know.....

`CURLOPT_CERTINFO` is being set correctly in the `psm_curl_get()` function, but there's some weird caveats that I'm noticing that don't seem to mesh up well? 

https://www.php.net/manual/en/function.curl-setopt.php And under `CURLOPT_CERTINFO` it says

> Added in cURL 7.19.1. Available since PHP 5.3.2. Requires `CURLOPT_VERBOSE` to be on to have an effect.

`CURLOPT_VERBOSE` is only being set in `psm_curl_get()` if `PSM_DEBUG` is true. So I set that guy to true and it still didn't work. Then looking closer and getting guidance from stackoverflow https://stackoverflow.com/questions/52974371/php-curl-empty-certinfo-with-certinfo-set-to-1

> TRUE to output SSL certification information to STDERR on secure transfers.

The code in `StatusUpdater.php` looks like this:
```php
<?php
        if (
            !empty($this->curl_info['certinfo']) &&
            $server['ssl_cert_expiry_days'] > 0
        ) {
                // run the checks, but it never gets here because curl_info['certinfo']
                //  is ALWAYS an empty array because the output is not sent to certinfo 
                //  but to STDERR
        }
```

So it just seems like the output from curl verbose needs to be captured and parsed in order to determine the certificates validity? Cause I do get the output in the verbose stuff, I just don't see it in the `$this->curl_info['certinfo']` key.

```
* About to connect() to mydomain.com port 443 (#2)
*   Trying 1.2.3.4...
* Connected to mydomain.com (1.2.3.4) port 443 (#2)
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
* Server certificate:
*       subject: CN=mydomain.com
*       start date: Feb 03 15:28:35 2020 GMT
*       expire date: May 03 15:28:35 2020 GMT #  <---- Totally expired.
*       common name: mydomain.com
*       issuer: CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
```
My only suggestion I guess at this point is should it be capturing STDERR, parsing it and then determining if the certificate is expired?

CentOS 7 (yum fully updated)
PHP 7.3
PHP Server Monitor v3.5.0

**Comment by wienfuchs** [comment] 2020-05-20 11:04
I've tried sending you a private mail requesting the URL of the failing server and got no response, so maybe your mail I found in your commits either does not work or my mail was sorted in your junk folder ;) Maybe you can let me know that info?
What I also guessed as possible source: Does the relevant server maybe contain a self-signed certificate?

**Comment by sicutdeux** [comment] 2020-05-20 14:05
Are you talking about me? the site in question is using letsencrypt cert, if you need the url, let me know.

**Comment by n0nag0n** [comment] 2020-05-20 15:04
If you're talking to me @wienfuchs no, it's not a self signed cert, it's letsencrypt and I know it's not a firewall issue because I do get a response from STDERR about my cert's info.

**Comment by wienfuchs** [comment] 2020-05-20 17:22
It was Austin (@n0nag0n) I tried to reach, but any "not working" site is welcome to me to help hunting down the problem. STDERR IMO is not really helpful, as - as it implies - is designed to catch error debugging info, not "misuse" as "workaround" - I would rather love to adress the source, not the debug ;)

**Comment by n0nag0n** [comment] 2020-05-20 17:35
I guess to me it seems really odd that curl would supply a key that would never have a value, but the documentation in PHP seems to conflict with what has been developed in here. I can't imagine a feature would be developed "hoping" for what data would be returned if in fact data was returned. I assume this has worked in the past on some distro with some version of curl, but I haven't (and a sad amount of other people on the web) figured out why the array key for certinfo is empty.

So I just tried it on my local machine (not where psm is installed) and I actually did get something back in the certinfo array. Looks like libcurl is 7.58 locally and 7.29 on the CentOS server. I'm just going to guess that this just may not work on CentOS 7 then.....

**Comment by wienfuchs** [comment] 2020-05-20 17:45
That indeed may be the source, as I also found an [similar description in a plesk forum](https://talk.plesk.com/threads/php-libcurl-fails-to-populate-certinfo-array.351354/)

**Comment by n0nag0n** [comment] 2020-05-20 18:53
Still weird that it'll populate in STDERR but not in the curlinfo array. Oh well :( Now I'll just go ahead and be really sad til I upgrade to centos 8

**Comment by wienfuchs** [comment] 2020-05-20 19:10
Okay, for the records: _Can_ be reproduced.

ToDo to reproduce:
- Setup a CentOS 7 host (checked with release 7.8.2003 in VirtualBox) with (remi) php7.3 (checked with7.3.18 as module)
- Setup latest phpservermon (checked with Latest commit ea33ba0)
- add any SSL website with SSL Certificate Validity "out of range" (e.g. 400 for sourceforge.net)
Voila, it does _not_ work as expected. Will further debug on this next time

**Comment by n0nag0n** [comment] 2020-05-20 20:29
Looks like the problem is definitely CentOS 7. https://bugzilla.redhat.com/show_bug.cgi?id=1684797 Upgrading curl seems to fix the problem. https://www.mysterydata.com/update-install-latest-curl-version-on-rhel-8-rhel-7-centos-7-8-cwp-vestacp-cpanel-plesk/. Now it at least shows that the SSL Certificate is expiring Never and all my sites are now orange haha instead of green haha. Progress???

**Comment by n0nag0n** [comment] 2020-05-20 20:37
Ooooohhhh fancy :) Looks like there's new errors with the names of the keys being changed :-/
```
PHP Notice:  Undefined index: Expire date in src/psm/Util/Server/Updater/StatusUpdater.php on line 429

Notice: Undefined index: Expire date in src/psm/Util/Server/Updater/StatusUpdater.php on line 429
PHP Notice:  Undefined index: Expire date in src/psm/Util/Server/Updater/StatusUpdater.php on line 437

Notice: Undefined index: Expire date in src/psm/Util/Server/Updater/StatusUpdater.php on line 437
```
Looks like it currently is looking for `Expire date` when the new key is `Expire Date` (capital D). This is on cURL 7.70 now. I can confirm that making that key change makes this work.

**Comment by wienfuchs** [comment] 2020-05-21 09:21
> Ooooohhhh fancy :) Looks like there's new errors with the names of the keys being changed :-/

That's quite easy to fix, pull request was entered to adress that issue.

For the older problem on CentOS 7 cURL 7.29 problem: As this is a CentOS/RedHat related source, it IMO should be fixed there (and the bug is adressed there).

**Comment by n0nag0n** [comment] 2020-05-21 14:50
At least until then, we could do something incredibly easy right? Something simple like the following would fix it for good:
```
$expire_date = $this->curlinfo['certinfo'][0]['Expire date'] ?? ($this->curlinfo['certinfo'][0]['Expire Date'] ?? false);
if($expire_date === false) {
   // error out somehow
}

// or make it even simpler with 
$expire_date_key = isset($this->curlinfo['certinfo'][0]['Expire date']) ? 'Expire date' : 'Expire Date';
// then use $expire_date_key in the code as it currently stands so it pulls from the right key.
```
It's just my opinion but it feels much easier to control it on PSM's end and not CentOS's end.

**Comment by n0nag0n** [comment] 2020-05-21 14:54
Made a comment, totally misreading your last post :) so I deleted it. Thanks for the fix! With the older CentOS problem, I agree, nothing we really can do about it, however some documentation somewhere (readme or wiki) just to point out a solution should someone want to care about that.

**Comment by wienfuchs** [comment] 2020-05-21 14:55
The solution to this is documented in this thread already ;) Upgrade cURL on CentOS 7 to higher than 7.29 is the solution on this - the other problem will be fixed by the commit.

**Comment by sicutdeux** [comment] 2020-05-21 19:14
Ok, here is a link with instructions on how to upgrade curl to 7.70, @wienfuchs let us know in which commit the other issue is resolved.

[Upgrade curl 7.70 on Centos 7](https://qiita.com/tkprof/items/5460b8d603cbbc542c8c
)

**Comment by wienfuchs** [comment] 2020-05-21 19:26
> @wienfuchs let us know in which commit the other issue is resolved.

https://github.com/phpservermon/phpservermon/pull/931 adresses this finally.

**Closed as completed** 2020-05-24 21:31 UTC
Labels: Type: bug
