### ISSUE TITLE
I have one web that shows offline and it isn't

### ISSUE THREAD

**Issue by XaRz** [phpservermon/phpservermon#669] opened 2018-10-18 16:48 UTC
Hello, 

Please anyone can test if www.interiorsa2.cat shows as offline in PSM 3.2?
I've discovered this software and for all others websites are working but for this don't. Any ideas?
I've installed in a pine64 without issues and seems working well for other websites but not this one, and I can't browse it without problems.

Any ideas?

Regards,

**Comment by mtelgkamp** [comment] 2019-01-30 15:20
The problem is that your domain is delivered via HTTP/2.0 thus this ticket is a duplicate of #672 (Problem with HTTP/2) and can be solved by Pull request #695 (Allow HTTP/2 status responses)

**Closed as completed** 2019-05-19 01:16 UTC
