### ISSUE TITLE
[Feature Request] Send notification via webhook

### ISSUE THREAD

**Issue by cyberjosh** [phpservermon/phpservermon#893] opened 2020-04-27 12:09 UTC
Hello, It would be lovely to receive notification via Webhook. This would allow my team to receive notification real time via Slack or AWS Chime. We are not able to monitor email all the time or sometimes email is down but slack is always up 100%.

**Comment by TimZ99** [comment] 2020-05-06 23:21
Duplicate of #255

**Closed as completed by TimZ99** 2020-05-06 23:21 UTC
Labels: Type: Feature
