### ISSUE TITLE
Public View

### ISSUE THREAD

**Issue by sterrenman** [phpservermon/phpservermon#312] opened 2016-05-31 21:13 UTC
Can a config option be added to allow viewing all server status without logging in?

**Comment by bastians** [comment] 2016-06-01 06:12
+1 - maybe it's possible with the planned API?

**Comment by sadortun** [comment] 2016-06-02 02:09
Duplicate of #51

**Comment by sadortun** [comment] 2016-06-02 02:10
Hi @sterrenman @bastians Feel free to submit a PR if you have some free time !

**Closed by sadortun** 2016-06-02 02:09 UTC
