### ISSUE TITLE
Add webhook  

### ISSUE THREAD

**Issue by hamelsveld** [phpservermon/phpservermon#832] opened 2020-01-14 09:24 UTC
I would be great to have 2 webhooks

1) sends all the data to a configurable host (for example a local logstash or elk stack for integration 

2) a configurable webhook for altering to other systems

Is this on the roadmap?

**Comment by TimZ99** [comment] 2020-01-14 09:52
Duplicate of #255. This is on the roadmap for v4, unless someone else adds this to v3.

**Closed as completed by TimZ99** 2020-01-14 09:52 UTC
Labels: duplicate
