### ISSUE TITLE
Monitor a website that require authentification 

### ISSUE THREAD

**Issue by hicham7575** [phpservermon/phpservermon#324] opened 2016-06-21 14:39 UTC
Hello,

I have to monitor a website that pops up an authentification box, it doestn't work with pattern because i have a blank page

**Comment by sadortun** [comment] 2016-06-21 16:33
Hi @hicham7575  This seems like a duplicate of #96 

What authentification are you talking about ?
Have you tried the last release of the `develop` ?

**Closed** 2016-10-21 14:44 UTC
Labels: duplicate, needs more info
