### ISSUE TITLE
Server with Website does not show positiv entry

### ISSUE THREAD

**Issue by holema** [phpservermon/phpservermon#664] opened 2018-10-06 12:11 UTC
Hello, first of all thank for this great Tool.
The modus to scan a server by Service is working great.
I want to track some servers, but with the modus Website I have no chance to track a website. I try to track your Webpage with this Settings:
![image](https://user-images.githubusercontent.com/22790152/46571205-268c0c80-c971-11e8-9abc-47da645ed00e.png)
But when I see it in the status window, I only can see that the server ist not sending a bad response, but no latency and no positiv result:
![image](https://user-images.githubusercontent.com/22790152/46571218-6b17a800-c971-11e8-9bfa-565bc10fc92d.png)
![image](https://user-images.githubusercontent.com/22790152/46571223-7d91e180-c971-11e8-8e38-6e063a91e0f4.png)
php-curl is installed
![image](https://user-images.githubusercontent.com/22790152/46571232-9f8b6400-c971-11e8-874e-b0d8a3afb08f.png)
I use V 3.4

**Comment by red-erik** [comment] 2018-10-09 09:18
Hi,
had the same problem and, for me, the only way to solve was to start from 3.3.1 and then upgrade to 3.4
regards.
Red.

**Comment by flaviomoringa** [comment] 2018-10-26 16:18
I did the upgrade as "red-erik" indicated and it seemed to work... but it did't.... initially it seemed it did, but then I realize that there were no new updates.... also when I tried to enter a website using POST it didn't work... always marking it as failed on the details... and on the status page no changes...

So I went back to 3.3.1... and it went back to work... it seems 3.4  it's not working... the new functionalities don't work (POST...) but it also breaks  the old ones.. not usable at all right now... but they seem really interesting... hope it can be made to work asap.

Thanks for this software....

**Comment by kenjilabs** [comment] 2018-10-28 06:36
Hi, I'm having the same issue, on database table psm_servers_uptime it is tracking the changes but it's not updating last_online column in psm_servers table

**Comment by mooleshacat** [comment] 2019-08-24 23:51
Not sure if it is related, but when I click "update" the website servers never update (the last check > 5 mins ago when cron runs minutely)

**Comment by TimZ99** [comment] 2019-09-19 15:15
So using POST as method breaks it?

**Comment by ghost** [comment] 2020-01-28 18:58
Currently having the same issues as described in the beggining by @holema
One server with the same version 3.4.5 works, and the other doesn;t. 
I am willing to debug or test any ideas.
Thank you!

And thank you for a great tool

EDIT:
Apparently the problem is fixed when building/cloning directly from source, not using the releases zip.

**Closed as completed** 2020-05-18 20:15 UTC
