### ISSUE TITLE
Implement more complex HTTP POST... requests with custom body

### ISSUE THREAD

**Issue by SciLor** [phpservermon/phpservermon#638] opened 2018-09-05 17:51 UTC
I have a JSON Webservice where I am expecting a specific result when I send a specific answer.

Positive case:
HTTP 400
{ "code": 123 }

Negative case:
HTTP 400
{ "code": 75 }

A workaround could be to allow a shellscript to make the check.

**Comment by TimZ99** [comment] 2018-09-05 18:18
#628 lets you mark HTTP 400 as online.
For the JSON part; why not use the pattern check?

**Comment by SciLor** [comment] 2018-09-05 19:06
I have to send a specific POST request to check if the service is online.
#628 would be also needed.

As I said as workaround I created a shellscript that is called by a php script that is checked by psm.

**Comment by TimZ99** [comment] 2018-09-05 19:35
#631 is also needed for this. Only an input field is needed and it's done.

**Comment by SciLor** [comment] 2018-09-05 19:45
Thank you for your quick answers. You may mark this one as duplicate of the others.

**Comment by TimZ99** [comment] 2018-09-05 19:57
It isn't a duplicate. The other issues don't include a post field.

Could you review #628 and #631? They need to be merged first.

**Comment by SciLor** [comment] 2018-09-05 20:00
What do you expect by review? Never did that before. They both look legit for me.

**Comment by TimZ99** [comment] 2018-09-05 20:05
Testing if the pr works as intended.

**Comment by TimZ99** [comment] 2018-09-05 20:05
If you use git, it's as easy as git checkout 'the branch' and opening your web browser.

**Comment by SciLor** [comment] 2018-09-05 20:08
Then just copy over the files to an (backuped) installation and check if its fine? I will try that on the weekend latest.

**Comment by TimZ99** [comment] 2018-09-05 20:25
You know what, I just merge them :sparkles:. That way I can work on this issue now :smile:.

**Comment by TimZ99** [comment] 2018-09-08 00:01
It's done btw :P

**Closed as completed** 2018-09-08 12:03 UTC

**Comment by SciLor** [comment] 2018-09-08 19:36
Can I just checkout the git and install it to my server?

**Comment by TimZ99** [comment] 2018-09-08 19:39
How do you have PSM installed? Did you clone using git or download the zip file?

**Comment by SciLor** [comment] 2018-09-08 19:41
I installed it via the zip file.

**Comment by TimZ99** [comment] 2018-09-08 19:48
- Download https://github.com/phpservermon/phpservermon/archive/develop.zip
- Remove all files from your PSM folder except config.php.
- Move files from the download to you PSM folder.
- Open PSM.

Please be aware that this version is not yet released and should be considered a beta.

**Comment by SciLor** [comment] 2018-09-08 19:58
I used the release zip for the installation of the last release. After following your instructions I now get "php composer.phar install" And on my testserver I am unable to login to a shell

**Comment by TimZ99** [comment] 2018-09-08 20:08
I will create a version with composer. wait a moment.

**Comment by TimZ99** [comment] 2018-09-08 20:20
<REMOVED FILE>

**Comment by SciLor** [comment] 2018-09-08 20:27
If I am creating a new server, no server entry is created in the "psm_servers" sql table. "Server added" popup comes up, but no new entry is visible.

**Comment by TimZ99** [comment] 2018-09-08 20:31
hmm, that's weird. Could you enable the debug mode?
add `define('PSM_DEBUG', 'true');` to config.php

**Comment by SciLor** [comment] 2018-09-08 20:34
<b>Warning</b>:  SQL error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'post_field' cannot be null in 

Seems to be an easy problem.

PS: I cannot copy paste on the gui of psm.

**Comment by TimZ99** [comment] 2018-09-08 20:36
I noticed that too but forgot to look into it. Could you make an issue for it?

**Comment by SciLor** [comment] 2018-09-08 20:40
done

**Comment by TimZ99** [comment] 2018-09-08 21:12
I meant for the copying part, but this one is also okay 👍

**Comment by SciLor** [comment] 2018-09-09 09:51
It seems to work, except that #628 won't work.
